name: python-helloworld

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: linux/amd64,linux/arm64

    steps:
    - uses: actions/checkout@v2
    - name: python-helloworld
      run: docker build . --file Dockerfile --tag lastest
